export const EVENT_NEW_HUB_REQUEST = "EVENT_NEW_HUB_REQUEST"
export const EVENT_NEW_HUB_CREATED = "EVENT_NEW_HUB_CREATED"
export const EVENT_HUB_CONNECT     = "EVENT_HUB_CONNECT"
export const EVENT_CLIENT_CONNECTED= "EVENT_CLIENT_CONNECTED"
export const EVENT_CLIENT_REMOVED  = "EVENT_CLIENT_REMOVED"
export const EVENT_HUB_REMOVED     = "EVENT_HUB_REMOVED"
export const EVENT_GET_CLIENTS     = "EVENT_GET_CLIENTS"
export const EVENT_GET_HUBS        = "EVENT_GET_HUBS"

export const EVENT_OFFER_CONNECTION     = "EVENT_OFFER_CONNECTION"
export const EVENT_ANSWER_CONNECTION    = "EVENT_ANSWER_CONNECTION"
export const EVENT_CANDIDATE_CONNECTION = "EVENT_CANDIDATE_CONNECTION"

export const EVENT_CLIENT_REPLY_REQUEST  = "EVENT_CLIENT_REPLY_REQUEST"
export const EVENT_CLIENT_REPLY_RESPONSE = "EVENT_CLIENT_REPLY_RESPONSE"

export const EVENT_ERROR   = "EVENT_ERROR"
export const EVENT_CONFIRM = "EVENT_CONFIRM"
    
export const ID_LENGTH = 12
export const RUNES = "0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"

export const STUN_TURN = null
export const SEND_DATA_CHANNEL = 'SEND_DATA_CHANNEL'

export const CHUNCK_SIZE = 16384;
